spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  sql:
    init:
      data-locations: classpath*:data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
      hibernate:
        SQL: DEBUG
        type: trace
server:
  servlet:
    encoding:
      force-response: true
cloud:
  aws:
    credentials:
      access-Key: ${AWS_ACCESS_KEY_ID}      # AWS IAM AccessKey 적기 ${AWS_ACCESS_KEY_ID}
      secret-Key: ${AWS_SECRET_ACCESS_KEY}   # AWS IAM SecretKey 적기 ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}  #${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false
mail:
  address:
    admin: ${ADMIN_EMAIL_ADDRESS}

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 4320
  refresh-token-expiration-minutes: 10080