import ProfileImg from "../src/assets/ProfileImg.png";

export const ClubDummyData = [
  {
    boardClubId: 2,
    memberId: 2,
    title: "자전거 동호회 모집합니다!",
    content: "서울지역에서 함께 자전거 타실 분을 찾습니다. 주로 주말에 활동합니다.",
    dueDate: "2023-08-15",
    contact: "https://open.kakao.com/456",
    view: 98,
    commentCount: 7,
    tags: [
      {
        tagName: "CYCLING",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-05",
    modifiedAt: "2023-07-06",
  },
  {
    boardClubId: 3,
    memberId: 3,
    title: "축구 동호회 찾습니다!",
    content: "축구를 좋아하시는 분들과 함께 활동할 동호회를 만들고자 합니다. 연락주세요!",
    dueDate: "2023-08-10",
    contact: "https://open.kakao.com/789",
    view: 75,
    commentCount: 3,
    tags: [
      {
        tagName: "SOCCER",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-02",
    modifiedAt: "2023-07-03",
  },
  {
    boardClubId: 4,
    memberId: 4,
    title: "등산 모임 모집합니다!",
    content: "함께 등산을 즐기실 분들을 찾습니다. 어려운 산은 아니니 많은 분들의 참여를 기다립니다.",
    dueDate: "2023-07-25",
    contact: "https://open.kakao.com/012",
    view: 120,
    commentCount: 10,
    tags: [
      {
        tagName: "HIKING",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-07",
    modifiedAt: "2023-07-08",
  },
  {
    boardClubId: 5,
    memberId: 5,
    title: "농구 동호회 찾습니다!",
    content: "농구를 좋아하는 분들과 함께 친목도 다지고 즐겁게 농구를 하고 싶습니다. 연락주세요!",
    dueDate: "2023-08-05",
    contact: "https://open.kakao.com/345",
    view: 86,
    commentCount: 6,
    tags: [
      {
        tagName: "BASKETBALL",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-04",
    modifiedAt: "2023-07-05",
  },
  {
    boardClubId: 6,
    memberId: 6,
    title: "배드민턴 동호회 모집합니다!",
    content: "주말에 배드민턴을 즐기실 분들을 찾습니다. 경험이 있으신 분들도 환영입니다.",
    dueDate: "2023-08-20",
    contact: "https://open.kakao.com/678",
    view: 112,
    commentCount: 9,
    tags: [
      {
        tagName: "BADMINTON",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-06",
    modifiedAt: "2023-07-07",
  },
  {
    boardClubId: 7,
    memberId: 7,
    title: "테니스 파트너 구합니다!",
    content: "서울 지역에서 주중에 테니스 칠 파트너를 찾습니다. 함께 즐겁게 운동해요!",
    dueDate: "2023-08-10",
    contact: "https://open.kakao.com/901",
    view: 78,
    commentCount: 4,
    tags: [
      {
        tagName: "TENNIS",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-03",
    modifiedAt: "2023-07-04",
  },
  {
    boardClubId: 8,
    memberId: 8,
    title: "체스 동호회 모집합니다!",
    content: "체스를 좋아하시는 분들과 함께 모여서 대회도 개최하고 싶습니다. 관심있으신 분들은 연락주세요.",
    dueDate: "2023-08-05",
    contact: "https://open.kakao.com/234",
    view: 92,
    commentCount: 6,
    tags: [
      {
        tagName: "CHESS",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-05",
    modifiedAt: "2023-07-06",
  },
  {
    boardClubId: 10,
    memberId: 10,
    title: "배구 동호회 모집합니다!",
    content: "서울지역에서 주말에 함께 배구를 즐길 동호회 멤버를 모집합니다. 연락주세요!",
    dueDate: "2023-08-10",
    contact: "https://open.kakao.com/890",
    view: 85,
    commentCount: 5,
    tags: [
      {
        tagName: "VOLLEYBALL",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-04",
    modifiedAt: "2023-07-05",
  },
  {
    boardClubId: 11,
    memberId: 11,
    title: "자유롭게 캠핑하는 모임입니다.",
    content: "캠핑을 좋아하시는 분들과 함께 자연 속에서 편안한 시간을 보내고 싶습니다. 많은 참여 부탁드립니다!",
    dueDate: "2023-08-20",
    contact: "https://open.kakao.com/678",
    view: 122,
    commentCount: 10,
    tags: [
      {
        tagName: "CAMPING",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-06",
    modifiedAt: "2023-07-07",
  },
  {
    boardClubId: 12,
    memberId: 12,
    title: "탁구 동호회 찾습니다!",
    content: "탁구를 즐기시는 분들과 함께 모여서 게임을 즐기고 실력을 향상시키고 싶습니다. 연락주세요!",
    dueDate: "2023-08-15",
    contact: "https://open.kakao.com/456",
    view: 96,
    commentCount: 8,
    tags: [
      {
        tagName: "TABLE TENNIS",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-05",
    modifiedAt: "2023-07-06",
  },
  {
    boardClubId: 13,
    memberId: 13,
    title: "모여서 풋살 하실 분 구합니다!",
    content: "풋살을 즐기실 분들을 찾습니다. 매주 토요일 오후에 모여서 즐거운 시간을 보내요.",
    dueDate: "2023-08-10",
    contact: "https://open.kakao.com/123",
    view: 80,
    commentCount: 6,
    tags: [
      {
        tagName: "FOOTBALL",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-03",
    modifiedAt: "2023-07-04",
  },
  {
    boardClubId: 14,
    memberId: 14,
    title: "테니스 스쿼시 파트너 구해요!",
    content: "스쿼시를 함께 칠 파트너를 찾습니다. 서울 지역에서 주중에 가능하신 분 연락주세요.",
    dueDate: "2023-08-05",
    contact: "https://open.kakao.com/789",
    view: 88,
    commentCount: 5,
    tags: [
      {
        tagName: "SQUASH",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-02",
    modifiedAt: "2023-07-03",
  },
  {
    boardClubId: 15,
    memberId: 15,
    title: "자전거 투어 같이 할 분 찾습니다!",
    content: "서울 주변 지역을 자전거로 함께 탐험할 투어 동호회를 만들고자 합니다. 관심있으신 분들은 연락주세요.",
    dueDate: "2023-08-15",
    contact: "https://open.kakao.com/012",
    view: 102,
    commentCount: 7,
    tags: [
      {
        tagName: "BIKE TOUR",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-05",
    modifiedAt: "2023-07-06",
  },
  {
    boardClubId: 16,
    memberId: 16,
    title: "요가 스튜디오 운영합니다!",
    content: "요가를 함께할 멤버를 찾습니다. 제주도에 위치한 스튜디오에서 다양한 요가 프로그램을 진행합니다.",
    dueDate: "2023-08-10",
    contact: "https://open.kakao.com/345",
    view: 90,
    commentCount: 4,
    tags: [
      {
        tagName: "YOGA",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-04",
    modifiedAt: "2023-07-05",
  },
  {
    boardClubId: 18,
    memberId: 18,
    title: "야구 동호회 모집합니다!",
    content: "서울지역에서 함께 야구를 즐길 동호회 멤버를 모집합니다. 실력과 나이에 상관없이 환영합니다.",
    dueDate: "2023-08-10",
    contact: "https://open.kakao.com/901",
    view: 79,
    commentCount: 3,
    tags: [
      {
        tagName: "BASEBALL",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-03",
    modifiedAt: "2023-07-04",
  },
  {
    boardClubId: 19,
    memberId: 19,
    title: "스케이트보드 동호회 찾습니다!",
    content: "서울에서 스케이트보드를 즐기는 분들과 모여서 함께 라이딩을 즐기고 실력을 향상시키고 싶습니다.",
    dueDate: "2023-08-15",
    contact: "https://open.kakao.com/234",
    view: 84,
    commentCount: 6,
    tags: [
      {
        tagName: "SKATEBOARDING",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-05",
    modifiedAt: "2023-07-06",
  },
  {
    boardClubId: 20,
    memberId: 20,
    title: "실내 클라이밍 동호회 찾습니다!",
    content: "실내 클라이밍을 좋아하는 분들과 함께 동호회를 만들어 즐겁게 클라이밍을 즐기고 싶습니다.",
    dueDate: "2023-08-05",
    contact: "https://open.kakao.com/567",
    view: 95,
    commentCount: 7,
    tags: [
      {
        tagName: "CLIMBING",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-04",
    modifiedAt: "2023-07-05",
  },

  {
    boardClubId: 21,
    memberId: 21,
    title: "런닝 동호회 구합니다!",
    content: "매주 토요일 아침에 함께 달리기를 즐기실 분들을 찾습니다. 서울지역에서 활동합니다.",
    dueDate: "2023-08-20",
    contact: "https://open.kakao.com/012",
    view: 100,
    commentCount: 8,
    tags: [
      {
        tagName: "RUNNING",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-06",
    modifiedAt: "2023-07-07",
  },

  {
    boardClubId: 22,
    memberId: 22,
    title: "배드민턴 대회 개최합니다!",
    content: "서울에서 배드민턴 대회를 개최하고자 합니다. 실력에 관계없이 많은 분들의 참가를 기다립니다.",
    dueDate: "2023-08-10",
    contact: "https://open.kakao.com/345",
    view: 89,
    commentCount: 5,
    tags: [
      {
        tagName: "BADMINTON",
      },
      {
        tagName: "TOURNAMENT",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-05",
    modifiedAt: "2023-07-06",
  },

  {
    boardClubId: 23,
    memberId: 23,
    title: "서핑 동호회 찾습니다!",
    content: "바다에서 서핑을 즐기는 분들과 함께 활동할 동호회를 만들고자 합니다. 관심있으신 분들은 연락주세요.",
    dueDate: "2023-08-15",
    contact: "https://open.kakao.com/678",
    view: 104,
    commentCount: 9,
    tags: [
      {
        tagName: "SURFING",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-07",
    modifiedAt: "2023-07-08",
  },

  {
    boardClubId: 24,
    memberId: 24,
    title: "테니스 훈련 모임 구합니다!",
    content: "테니스를 좋아하시는 분들과 함께 훈련을 진행할 모임을 구합니다. 실력 향상을 위해 노력하고 싶습니다.",
    dueDate: "2023-08-05",
    contact: "https://open.kakao.com/901",
    view: 81,
    commentCount: 4,
    tags: [
      {
        tagName: "TENNIS",
      },
      {
        tagName: "TRAINING",
      },
    ],
    boardClubStatus: "BOARD_CLUB_RECRUITING",
    createdAt: "2023-07-03",
    modifiedAt: "2023-07-04",
  },
];
export const ClubDetailMockData = {
  boardClubId: 2,
  memberId: 2,
  title: "자전거 동호회 모집합니다!",
  content: "서울지역에서 함께 자전거 타실 분을 찾습니다. 주로 주말에 활동합니다.",
  dueDate: "2023-08-15",
  contact: "https://open.kakao.com/456",
  view: 98,
  commentCount: 7,
  tags: [
    {
      tagName: "CYCLING",
    },
  ],
  boardClubStatus: "BOARD_CLUB_RECRUITING",
  createdAt: "2023-07-05",
  modifiedAt: "2023-07-06",
};

export const Mocktags: Array<string> = [
  "전체",
  "다이빙",
  "스노클링",
  "플라이보드",
  "웨이크보드",
  "패들보드",
  "플라이피시",
  "수상스키",
  "바나나보트",
  "카이트서핑",
  "카약&카누",
];

export const CommunityPopularMockdata = [
  {
    memberId: 1,
    memberProfileImg: ProfileImg,
    name: "닉네임이길어어어어",
    title: "아무제목이나~~",
    content: "가나다라마바사아자차가나다라마바사아자차가나다라마...",
    tag: "카이트서핑",
    view: 200,
    registeredAt: "2023-06-16T13:42:42.528845",
    modifiedAt: "2023-06-16T13:42:42.528845",
    like: 5,
    commentCount: 3,
    memberLiked: [1, 2, 3],
    standardId: 1,
  },
  {
    memberId: 1,
    memberProfileImg: ProfileImg,
    name: "닉네임1",
    title: "아무제목이나~~",
    content: "가나다라마바사아자차가나다라마바사아자차가나다라마...",
    tag: "스쿠버다이빙",
    view: 110,
    registeredAt: "2023-06-16T13:42:42.528845",
    modifiedAt: "2023-06-16T13:42:42.528845",
    like: 5,
    commentCount: 3,
    memberLiked: [2, 3],
    standardId: 2,
  },
  {
    memberId: 3,
    memberProfileImg: ProfileImg,
    name: "닉네임1",
    title: "아무제목이나~~",
    content: "가나다라마바사아자차가나다라마바사아자차가나다라마...",
    tag: "카약&카누",
    view: 123,
    registeredAt: "2023-06-16T13:42:42.528845",
    modifiedAt: null,
    like: 5,
    commentCount: 3,
    memberLiked: [1, 2, 3],
    standardId: 3,
  },
];
